services:
  autogen:
    build: ./autogen
    extra_hosts:
        - "host.docker.internal:host-gateway"
    ports:
      - "4000:4000"
  searxng:
    image: searxng/searxng:latest
    container_name: searxng
    ports:
      - 8080:8080
    volumes:
      - ./searxng:/etc/searxng
  jupyter:
    build: 
      context: ./jupyter
    ports: 
      - 8888:8888
    volumes:
      - ./data:/workspace/data
      - ./jupyter/notebooks/:/workspace/notebooks/
      - ~/.cache/:/root/.cache/
